### ISSUE TITLE
Design a home Page in ReactJs

### ISSUE THREAD

**Issue by ZiaCodes** [ZiaCodes/claim-prize#17]
Design a Landing page for the application with ReactJs 
You can use any css framework or lib you want.

Reference : - 
<div align="left">
<img src="https://raw.githubusercontent.com/ZiaCodes/img_server/main/others/cliamswag.png" alt="Banner" width="40%"/>
</div>

**Comment by Aniket-508** [comment]
I want to work on this! @ZiaCodes

**Comment by ZiaCodes** [comment]
> I want to work on this! @ZiaCodes

Okay @Aniket-508 good luck

**Comment by KushalGhosh9899** [comment]
I want to work on this issue under JWOC

**Comment by ZiaCodes** [comment]
> I want to work on this issue under JWOC

Okay Assigned
