### ISSUE TITLE
Design a User info Page

### ISSUE THREAD

**Issue by ZiaCodes** [ZiaCodes/claim-prize#18]
Design a User info Page in reactjs and link it in about section.

reference : -

**Comment by SriramSonaganti** [comment]
i want to work on this under JWOC.

Can i get some detailed information.

**Comment by ZiaCodes** [comment]
> i want to work on this under JWOC.
> 
> Can i get some detailed information.

Yeah Sure let me update the reference

**Comment by SriramSonaganti** [comment]
can you update the reference and assign me

**Comment by ZiaCodes** [comment]
> can you update the reference and assign me

You can design accoring to this theme 
<img src="https://user-images.githubusercontent.com/78309659/153561679-b601bda5-06f2-44c7-b480-1fe5d0ab925b.png" >

**Comment by SriramSonaganti** [comment]
> > can you update the reference and assign me
> 
> You can design accoring to this theme ![](https://user-images.githubusercontent.com/78309659/153561679-b601bda5-06f2-44c7-b480-1fe5d0ab925b.png)

I think the isuse is labelled as user info page but if you have posted register page could you please confirm.? or do you mean it should have a transparent theme?

**Comment by ZiaCodes** [comment]
> > > can you update the reference and assign me
> > 
> > 
> > You can design accoring to this theme ![](https://user-images.githubusercontent.com/78309659/153561679-b601bda5-06f2-44c7-b480-1fe5d0ab925b.png)
> 
> I think the isuse is labelled as user info page but if you have posted register page could you please confirm.? or do you mean it should have a transparent theme?

Exactly , i told to take the theme only , you can look into the Schema from the backend (form.js) and start implementing those field into this one...

**Comment by KushalGhosh9899** [comment]
I want to work on this issue under JWOC @ZiaCodes

**Comment by ZiaCodes** [comment]
> I want to work on this issue under JWOC @ZiaCodes

okay cool
