### ISSUE TITLE
Implement a Email Notification feature

### ISSUE THREAD

**Issue by ZiaCodes** [ZiaCodes/claim-prize#2]
Implement a Email Notification feature for everyone who register for the first time.

You can use any free Email services such as Node Mailer .

Use Postman for testing if there is no client UI.

Note: Before making pull request make sure you have done all the work and please add some necessary gifs and photos.

**Comment by AnandSY** [comment]
"I want to work on this issue under JWOC"

**Comment by ZiaCodes** [comment]
> "I want to work on this issue under JWOC"

Great , You are Assigned , Good luck

**Comment by privateyash** [comment]
"I want to work on this issue under JWOC"

**Comment by Aniket-508** [comment]
I want to work on this under JWoC.

**Comment by ZiaCodes** [comment]
> I want to work on this under JWoC.

Okay done ✅

**Comment by ZiaCodes** [comment]
> > I want to work on this under JWoC.
> 
> Hey it has been already implemented , Can you work on client side for this one ??
