### ISSUE TITLE
Design a register page 

### ISSUE THREAD

**Issue by ZiaCodes** [ZiaCodes/claim-prize#20]
Design a register page in reactjs

reference you can take - 

<img src="https://raw.githubusercontent.com/ZiaCodes/img_server/main/others/register.png" alt="Banner" width="50%"/>

**Comment by Mainakroy050** [comment]
hi! 
I want to work on this issue under JWOC

**Comment by ZiaCodes** [comment]
> hi! I want to work on this issue under JWOC

Yeah sure
