### ISSUE TITLE
Store a session Cookies when user login on signIn Page.

### ISSUE THREAD

**Issue by ZiaCodes** [ZiaCodes/claim-prize#3]
Store a session Cookies when user  signIn  using Json Web Token.

JWT Documentation : https://jwt.io/

Before making pull request make sure you have done all the work and please add some necessary gifs and photos.

**Comment by HASH-002** [comment]
"I want to work on this issue under JWOC"

**Comment by ZiaCodes** [comment]
> "I want to work on this issue under JWOC"

You can not work more than two issue at the same time. First finish your issues then move into the other ..
Thank you

**Comment by ChandreshBabu** [comment]
"I want to work on this issue under JWOC"

**Comment by ZiaCodes** [comment]
> "I want to work on this issue under JWOC"

Okay assigned good luck

**Comment by ChandreshBabu** [comment]
Hi, what do you want me to do exactly, cause token is alraedy being created and cookie is being set and stored already. There may be this issue that token is bieng created and stored every time and being stored even user enters wrong password, is it the issue exactly.

**Comment by ZiaCodes** [comment]
> 

You have to add the token when user successfully login through signin routes , Work on frontend ...

**Comment by SriramSonaganti** [comment]
"i want to work on this under JWOC"

**Comment by ZiaCodes** [comment]
> "i want to work on this under JWOC"

Okay assigned and make sure you add some demo for a better visualization

**Comment by adityarathore063** [comment]
I want to work on this issue under JWOC
