### ISSUE TITLE
Add a logout Feature

### ISSUE THREAD

**Issue by ZiaCodes** [ZiaCodes/claim-prize#4]
Add a log out feature like when a user wants to logout from the application they can do it with a simple button 

Note: Before Making a pull request make sure you have done everything necessary and please add gifs and photos for better visualization.

**Comment by HASH-002** [comment]
"I want to work on this issue under JWOC"

**Comment by AnandSY** [comment]
"I want to work on this issue under JWOC"

**Comment by ZiaCodes** [comment]
> "I want to work on this issue under JWOC"

Good Luck

**Comment by ZiaCodes** [comment]
> "I want to work on this issue under JWOC"

You can work on another is

**Comment by privateyash** [comment]
"I want to work on this issue under JWOC"

**Comment by ZiaCodes** [comment]
> "I want to work on this issue under JWOC"

I will assign you after 2 hours if the current one will not solve within the time

**Comment by SriramSonaganti** [comment]
i want to work on this under "JWOC" if this is still open.

**Comment by privateyash** [comment]
can you pls assign me
@ZiaCodes

**Comment by ZiaCodes** [comment]
> can you pls assign me @ZiaCodes

Assigned

**Comment by SriramSonaganti** [comment]
Is this still an open issue if so i would like to work under Jwoc 
can you assign me @ZiaCodes
