### ISSUE TITLE
Forget Password Functionality 

### ISSUE THREAD

**Issue by ZiaCodes** [ZiaCodes/claim-prize#5]
If you don't find any UI Client side then you have to make it . Frontend should be in reactJs only
Note: Before Making an pull request make sure you have done everything necessary and please add gifs and photos for better visualization.

**Comment by harshit-070** [comment]
I want to work on this issue under JWOC

**Comment by ZiaCodes** [comment]
> I want to work on this issue under JWOC

Okay good luck

**Comment by SriramSonaganti** [comment]
I want to work on this issue under JWOC

**Comment by ZiaCodes** [comment]
> I want to work on this issue under JWOC

Okay assigning
